### ISSUE TITLE
about the result

### ISSUE THREAD

**Issue by zmm96** [smehdia/NTIRE2021-IQA-MACS#2]
Thanks for your open source, could I knew the result of your test dataset (plcc and srcc)?

**Comment by smehdia** [comment]
Sure,
You can find them in our paper:
https://arxiv.org/pdf/2105.02531.pdf

**Comment by Seyed-Ali-Ahmadi** [comment]
How can I give two images (reference and test) and get the attention of the model on the image?

**Comment by smehdia** [comment]
@Seyed-Ali-Ahmadi  You can follow the instuctions here to get the attention maps: https://www.pyimagesearch.com/2020/03/09/grad-cam-visualize-class-activation-maps-with-keras-tensorflow-and-deep-learning/
